export default {
    menuTreeDatas() {
        return [
            {key:"index",label:"首页",menuType:0,isUserSetup:true,route:""},
            {key:"userCenter",label:"用户中心",menuType:0,route:"",isUserSetup:false,items:[
                    {key:"userWork",label:"上传作品",route:""},
                    {key:"userMsg",label:"我的消息",route:""}
                ]},
            {key:"pingJiang",label:"评奖",menuType:1,route:"",isUserSetup:true,items:[
                    {key:"pingWei",label:"评委",isUserSetup:true,route:""},
                    {key:"pingShenBiaoZun",label:"评审标准",isUserSetup:true,route:""}
                ]},
            {key:"huoJiangWork",label:"获奖作品",menuType:1,route:"",isUserSetup:true,items:[
                    {key:"storyWork",label:"历届获奖作品",isUserSetup:true,route:""},
                    {key:"theWork",label:"本次获奖作品",isUserSetup:true,route:""}
                ]},
            {key:"news",label:"新闻",menuType:0,route:""}
        ]
    },
    uiIndexJson() {
        return {
            bannerArea:{
                name:"轮播区域",
                setup:{
                    banner:{type:"box",pre:"设置轮播",value:[],eltTypes:[{type:"image",pre:"图片"},{type:"text",pre:"URL"},{type:"title",pre:"Title"},{type:"text",pre:"内容"}]},
                    mImg:{type:"image",src:"",pre:"中间信息图片"}
                }
            },
            sloganArea:{
                name:"广告语区域",
                setup:{
                    bgImg:{type:"image",src:"",pre:"背景图"},
                    title:{type:"text",value:"",pre:"标题"},
                    subtitle:{type:"text",value:"",pre:"副标题"}
                }
            },
            jiangArea:{
                name:"奖项",
                setup:{
                    title:{type:"headTitle",value:"奖项",pre:"标题名称"},
                    jiangItems:{type:"box",pre:"设置各奖项",value:[],eltTypes:[{type:"jbText",pre:"名称",props:{}},{type:"text",pre:"得奖数量文字(如：每组1名)"},{type:"text",pre:"奖金奖杯文字(如：奖金2000元)"},{type:"text",pre:"奖品文字(如：某品牌生态照明设备)"}]}
                }
            },
            judgeArea:{
                name:"评委",
                setup:{
                    title:{type:"headTitle",value:"评委",pre:"标题名称"},
                    judgeItems:{type:"box",pre:"设置评委信息",value:[],eltTypes:[{type:"text",pre:"姓名"},{type:"text",pre:"一句话介绍(如：xxx公司创始人)"},{type:"text",pre:"职位(如：xxx协会秘书长)"}]}
                }
            },
            workStoreArea:{
                name:"往届获奖作品",
                setup:{
                    title:{type:"headTitle",value:"往届获奖作品",pre:"标题名称"},
                    mImg:{type:"image",src:"",pre:"滚动图片"}
                }
            },
            newsArea:{
                name:"最新动态",
                setup:{
                    title:{type:"headTitle",value:"最新动态",pre:"标题名称"},
                    newsItems:{type:"box",pre:"设置最新动态",value:[],eltTypes:[{type:"image",pre:"图片"},{type:"text",pre:"名称"},{type:"date",pre:"日期",format:"yyyy-mm-dd"}]}
                }
            },
            orgArea:{
                name:"联合主办机构",
                setup:{
                    title:{type:"headTitle",value:"联合主办机构",pre:"标题名称"},
                    orgItems:{type:"box",pre:"设置联合主办机构",value:[],eltTypes:[{type:"image",pre:"图片"},{type:"text",pre:"URL"}]}
                }
            },
            boundArea:{
                name:"赞助品牌",
                setup:{
                    title:{type:"headTitle",value:"赞助品牌",pre:"标题名称"},
                    boundItems:{type:"box",pre:"设置赞助品牌",value:[],eltTypes:[{type:"image",pre:"图片"},{type:"text",pre:"URL"}]}
                }
            }
        }
    }
}