server:
  port: 8080
  servlet:
    context-path: /edu
  tomcat:
    accesslog:
      enabled: true
      pattern: '%{yyyy-MM-dd HH:mm:ss}t %a %A %m %s %D %b %I %U%q %{User-Agent}i'
      suffix: .log
      prefix: access_log
      directory: tomcat_log
spring:
  main:
    banner-mode: "off"
    allow-circular-references: true
  jmx:
    default-domain: edu
  jersey:
    servlet:
      load-on-startup: 1
  datasource:
    url: "jdbc:postgresql://localhost:5432/alicedb"
    username: "juser"
    password: "weav2880com"
    camunda:
      url: "jdbc:postgresql://localhost:5432/camunda"
      username: "juser"
      password: "weav2880com"
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: Weav2880com
      timeout: 60s        # 连接空闲超过N(s秒、ms毫秒，不加单位时使用毫秒)后关闭，0为禁用，这里配置值和tcp-keepalive值一致
#       Lettuce连接池配置
      lettuce:
        pool:
          max-active: 10  # 允许最大连接数，默认8（负值表示没有限制），推荐值：大于cpu * 2，通常为(cpu * 2) + 2
          max-idle: 8     # 最大空闲连接数，默认8，推荐值：cpu * 2
          min-idle: 0     # 最小空闲连接数，默认0
          max-wait: 5s    # 连接用完时，新的请求等待时间(s秒、ms毫秒)，超过该时间抛出异常，默认-1（负值表示没有限制）
        cluster:
          refresh:
            adaptive: true
            period: 20
  devtools:
    restart:
      enabled: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org:
      springframework: error
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
  pattern:
    level:
    file:
    console: '%clr(%d{HH:mm:ss}){yellow} [%clr(%thread){red}] %-5level --- %clr(%logger){green} | %msg%n'
camunda.bpm:
  webapp:
    application:
      path: /camunda/app
  admin-user:
    id: justinhujf
    password: hjfhjf